packages:
  - 'chrome-extension'
  - 'pages/*'
  # - 'pages/content/*'
  - 'packages/*'
  - 'tests/*'
allowBuilds:
  '@firebase/util': true
  '@swc/core': true
  esbuild: true
  protobufjs: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.10.10'
  - '@turbo/darwin-arm64@2.10.10'
  - '@turbo/linux-64@2.10.10'
  - '@turbo/linux-arm64@2.10.10'
  - '@turbo/windows-64@2.10.10'
  - '@turbo/windows-arm64@2.10.10'
  - turbo@2.10.10
